version: '3.8'

services:
  data-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-processing-agent
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - DATA_SOURCE=sales_data
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - agent-network
    restart: unless-stopped

  # Serviço opcional para simular uma API externa
  mock-api:
    image: nginx:alpine
    container_name: mock-api-service
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - agent-network
    restart: unless-stopped

networks:
  agent-network:
    driver: bridge

volumes:
  data-volume:
  logs-volume: 